
import React, { useState, useMemo } from 'react';
import { X, Code, Clipboard, Check, Download, Puzzle, FileCode } from 'lucide-react';
import { useModpack } from '../context/ModpackContext';
import { useI18n } from '../App';
import { Recipe, RecipeProcessor, MachineDefinition, Resource } from '../types';

interface CodeGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const CodeGeneratorModal: React.FC<CodeGeneratorModalProps> = ({ isOpen, onClose }) => {
  const { recipes, machines, resources, plugins } = useModpack();
  const { t } = useI18n();
  const [selectedProcId, setSelectedProcId] = useState<string>('');
  const [copied, setCopied] = useState(false);

  const allProcessors = useMemo(() => {
    return plugins.flatMap(p => p.processors);
  }, [plugins]);

  const selectedProcessor = useMemo(() => {
    return allProcessors.find(p => p.id === selectedProcId);
  }, [allProcessors, selectedProcId]);

  const generatedCode = useMemo(() => {
    if (!selectedProcessor) return '';

    const header = `/**\n * Generated by Modpack Architect\n * Processor: ${selectedProcessor.name}\n * Date: ${new Date().toLocaleString()}\n */\n\n`;
    
    const snippets = recipes.map(recipe => {
      const machine = machines.find(m => m.id === recipe.machineId);
      if (!machine) return `// Error: Machine not found for recipe ${recipe.id}`;

      try {
        if (selectedProcessor.handler) {
          return selectedProcessor.handler(recipe, machine, resources);
        }
        
        // Template Fallback
        let output = selectedProcessor.template || "";
        const inputIds = recipe.inputs.map(i => `"${i.resourceId}"`).join(', ');
        const outputIds = recipe.outputs.map(o => `"${o.resourceId}"`).join(', ');
        output = output.replace(/\{\{machine\}\}/g, machine.id);
        output = output.replace(/\{\{input_ids\}\}/g, `[${inputIds}]`);
        output = output.replace(/\{\{output_ids\}\}/g, `[${outputIds}]`);
        output = output.replace(/\{\{duration\}\}/g, String(recipe.duration || 100));
        return output;
      } catch (e) {
        return `// Processor Error on recipe ${recipe.id}: ${e instanceof Error ? e.message : 'Unknown'}`;
      }
    });

    return header + snippets.join('\n\n');
  }, [selectedProcessor, recipes, machines, resources]);

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([generatedCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `recipes_${selectedProcId || 'export'}.js`;
    link.click();
    URL.revokeObjectURL(url);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[150] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/80 backdrop-blur-xl transition-opacity" onClick={onClose} />
      <div className="relative w-full max-w-5xl bg-zinc-900 border border-zinc-800 rounded-[2.5rem] shadow-2xl flex flex-col max-h-[90vh] overflow-hidden animate-in fade-in zoom-in-95 duration-300">
        
        <div className="flex items-center justify-between px-10 py-8 border-b border-zinc-800 shrink-0">
          <div className="flex items-center gap-4">
             <div className="bg-emerald-600 p-3 rounded-2xl shadow-lg shadow-emerald-600/20">
                <Code size={24} className="text-white" />
             </div>
             <div>
                <h2 className="text-2xl font-black text-white uppercase tracking-[0.1em]">{t('modal.generateCode')}</h2>
                <p className="text-xs text-zinc-500 font-bold uppercase tracking-widest mt-1 opacity-60">{recipes.length} Recipes Total</p>
             </div>
          </div>
          <button onClick={onClose} className="p-3 text-zinc-600 hover:text-white hover:bg-zinc-800 rounded-2xl transition-all"><X size={24} /></button>
        </div>

        <div className="flex-1 overflow-hidden flex flex-col p-10 gap-10">
           <div className="space-y-4 shrink-0">
              <label className="text-[11px] font-black text-zinc-500 uppercase tracking-widest ml-1">{t('modal.selectProcessor')}</label>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 max-h-48 overflow-y-auto pr-2 custom-scrollbar">
                {allProcessors.length > 0 ? allProcessors.map(proc => (
                  <button 
                    key={proc.id} 
                    onClick={() => setSelectedProcId(proc.id)}
                    className={`flex items-start gap-4 p-5 rounded-2xl border transition-all text-left ${
                      selectedProcId === proc.id 
                        ? 'bg-blue-600/10 border-blue-500 shadow-xl shadow-blue-600/5' 
                        : 'bg-zinc-950/40 border-zinc-800 hover:border-zinc-700'
                    }`}
                  >
                    <div className={`p-3 rounded-xl ${selectedProcId === proc.id ? 'bg-blue-600 text-white' : 'bg-zinc-800 text-zinc-500'}`}>
                       <Puzzle size={20} />
                    </div>
                    <div>
                       <div className={`text-sm font-black uppercase tracking-wide ${selectedProcId === proc.id ? 'text-white' : 'text-zinc-300'}`}>{proc.name}</div>
                       <p className="text-[10px] text-zinc-500 line-clamp-1 mt-0.5">{proc.description}</p>
                    </div>
                  </button>
                )) : (
                  <div className="col-span-full py-10 flex flex-col items-center justify-center border-2 border-dashed border-zinc-800 rounded-3xl opacity-30">
                     <Puzzle size={40} className="mb-3" />
                     <p className="text-xs font-black uppercase tracking-widest">No Processors Available</p>
                  </div>
                )}
              </div>
           </div>

           <div className="flex-1 min-h-0 flex flex-col space-y-4">
              <div className="flex items-center justify-between ml-1">
                 <label className="text-[11px] font-black text-zinc-500 uppercase tracking-widest">{t('modal.preview')}</label>
                 <div className="flex items-center gap-3">
                    <button 
                      onClick={handleCopy} 
                      disabled={!generatedCode}
                      className="flex items-center gap-2 px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all disabled:opacity-30"
                    >
                      {copied ? <Check size={14} className="text-emerald-500" /> : <Clipboard size={14} />}
                      {t('common.copy')}
                    </button>
                    <button 
                      onClick={handleDownload}
                      disabled={!generatedCode}
                      className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-[10px] font-black uppercase tracking-widest transition-all shadow-lg shadow-blue-600/20 disabled:opacity-30"
                    >
                      <Download size={14} />
                      {t('common.download')}
                    </button>
                 </div>
              </div>
              <div className="flex-1 bg-zinc-950 rounded-3xl border border-zinc-800 overflow-hidden relative group">
                 <pre className="absolute inset-0 p-8 overflow-auto text-xs text-zinc-400 font-mono leading-relaxed custom-scrollbar whitespace-pre-wrap">
                    {generatedCode || '// Select a processor to generate code...'}
                 </pre>
                 <div className="absolute top-8 right-8 pointer-events-none opacity-5">
                    <FileCode size={120} className="text-white" />
                 </div>
              </div>
           </div>
        </div>

      </div>
    </div>
  );
};

export default CodeGeneratorModal;
